### ISSUE TITLE
Long time no update!

### ISSUE THREAD

**Issue by tom-seddon** [popey/b2-snap#1]
I noticed the latest version is from August 2020: https://snapcraft.io/b2 - but there have been new updates pushed to the b2 master branch since then! Did this fall foul of the Travis CI changeover? Or did I break something?

I'm not sure how to investigate.

Thanks,

--Tom

**Comment by popey** [comment]
Sorry for the delay in replying @tom-seddon - the snap is now up to date, and it is getting continuous updates as you do releases <3
